leproperties: create etc/build.prop during runtime
Install leprop.conf for creating etc/build.prop file at
run-time using systemd-tmpfiles.

Resolves error:
Error: leprop-service[pid]: Persist File doesnt exist

Root cause:
ll.c FILE *fp = fopen(PROP_FILE_PERSIST_PATH, "w");

- leprop.service runs with user/group leprop
- leprop.service doesn't have root priviledges to modify build.prop (which is root attribute)
- Update properties of build.prop to allow leprop user/group to access it.

Change-Id: Ia6f01799a4b40c1b1c2b7463c34117be03499e99